services:
  valkey:
    image: valkey/valkey:latest
    command: [ "valkey-server", "--appendonly", "yes", "--dir", "/data" ]
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data

volumes:
  valkey_data:
