"""initial document tables

Revision ID: 95d307699246
Revises:
Create Date: 2026-04-23 00:24:56.946974+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "95d307699246"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_types",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "metadata_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "metadata_defaults", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "workflow_jobs",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("request_key", sa.String(length=255), nullable=False),
        sa.Column("workflow_type", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("event_source", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("source_set_key", sa.String(length=255), nullable=True),
        sa.Column("revision_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("reject_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_feedback_summary", sa.Text(), nullable=True),
        sa.Column(
            "job_details", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_key"),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("artifact_kind", sa.String(length=64), nullable=False),
        sa.Column("document_type_id", sa.UUID(), nullable=False),
        sa.Column("storage_uri", sa.String(length=1024), nullable=False),
        sa.Column(
            "visibility",
            sa.Enum(
                "public",
                "internal",
                "private",
                name="document_visibility",
                native_enum=False,
            ),
            server_default="public",
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("current_content_hash", sa.String(length=255), nullable=True),
        sa.Column("source_hash", sa.String(length=255), nullable=True),
        sa.Column("source_uri", sa.String(length=1024), nullable=True),
        sa.Column("source_set_key", sa.String(length=255), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("topics", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("people", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("organizations", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("projects", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_type_id"], ["document_types.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_uri"),
    )
    op.create_index(
        op.f("ix_documents_current_content_hash"),
        "documents",
        ["current_content_hash"],
        unique=False,
    )
    op.create_index(
        "ix_documents_metadata_gin",
        "documents",
        ["metadata"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_documents_organizations_gin",
        "documents",
        ["organizations"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_documents_people_gin",
        "documents",
        ["people"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_documents_projects_gin",
        "documents",
        ["projects"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_documents_source_hash"), "documents", ["source_hash"], unique=False
    )
    op.create_index(
        op.f("ix_documents_source_set_key"),
        "documents",
        ["source_set_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documents_source_uri"), "documents", ["source_uri"], unique=False
    )
    op.create_index(
        "ix_documents_tags_gin",
        "documents",
        ["tags"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_documents_topics_gin",
        "documents",
        ["topics"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "workflow_job_transitions",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("from_status", sa.String(length=64), nullable=True),
        sa.Column("to_status", sa.String(length=64), nullable=False),
        sa.Column("transition_reason", sa.Text(), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "transitioned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["workflow_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_job_transitions_job_id"),
        "workflow_job_transitions",
        ["job_id"],
        unique=False,
    )
    op.create_table(
        "compiled_documents",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("compiled_document_id", sa.String(length=255), nullable=False),
        sa.Column("compiled_document_hash", sa.String(length=255), nullable=True),
        sa.Column("compiled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_document_uris", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("source_content_hashes", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("source_hashes", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("source_uris", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("review_feedback", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column(
            "compile_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("document_id"),
    )
    op.create_index(
        op.f("ix_compiled_documents_compiled_document_hash"),
        "compiled_documents",
        ["compiled_document_hash"],
        unique=False,
    )
    op.create_table(
        "document_job_links",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("edit_type", sa.String(length=64), nullable=False),
        sa.Column("edit_count", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "first_edit_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_edit_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["workflow_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_id",
            "job_id",
            "edit_type",
            name="uq_document_job_links_document_job_edit_type",
        ),
    )
    op.create_index(
        op.f("ix_document_job_links_document_id"),
        "document_job_links",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_job_links_job_id"),
        "document_job_links",
        ["job_id"],
        unique=False,
    )
    op.create_table(
        "document_vector_refs",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("backend_name", sa.String(length=128), nullable=False),
        sa.Column("collection_name", sa.String(length=255), nullable=True),
        sa.Column("namespace", sa.String(length=255), nullable=True),
        sa.Column("external_document_id", sa.String(length=255), nullable=True),
        sa.Column("chunk_id", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_vector_refs_document_id"),
        "document_vector_refs",
        ["document_id"],
        unique=False,
    )
    op.create_table(
        "published_pages",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("published_page_id", sa.String(length=255), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("compiled_document_ids", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column(
            "compiled_document_uris", postgresql.ARRAY(sa.Text()), nullable=False
        ),
        sa.Column("source_set_keys", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column(
            "page_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("document_id"),
    )
    op.create_table(
        "raw_documents",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("source_type", sa.String(length=255), nullable=False),
        sa.Column("source_id", sa.String(length=255), nullable=True),
        sa.Column("content_type", sa.String(length=255), nullable=True),
        sa.Column(
            "source_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("raw_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("document_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("raw_documents")
    op.drop_table("published_pages")
    op.drop_index(
        op.f("ix_document_vector_refs_document_id"), table_name="document_vector_refs"
    )
    op.drop_table("document_vector_refs")
    op.drop_index(op.f("ix_document_job_links_job_id"), table_name="document_job_links")
    op.drop_index(
        op.f("ix_document_job_links_document_id"), table_name="document_job_links"
    )
    op.drop_table("document_job_links")
    op.drop_index(
        op.f("ix_compiled_documents_compiled_document_hash"),
        table_name="compiled_documents",
    )
    op.drop_table("compiled_documents")
    op.drop_index(
        op.f("ix_workflow_job_transitions_job_id"),
        table_name="workflow_job_transitions",
    )
    op.drop_table("workflow_job_transitions")
    op.drop_index(
        "ix_documents_topics_gin", table_name="documents", postgresql_using="gin"
    )
    op.drop_index(
        "ix_documents_tags_gin", table_name="documents", postgresql_using="gin"
    )
    op.drop_index(op.f("ix_documents_source_uri"), table_name="documents")
    op.drop_index(op.f("ix_documents_source_set_key"), table_name="documents")
    op.drop_index(op.f("ix_documents_source_hash"), table_name="documents")
    op.drop_index(
        "ix_documents_projects_gin", table_name="documents", postgresql_using="gin"
    )
    op.drop_index(
        "ix_documents_people_gin", table_name="documents", postgresql_using="gin"
    )
    op.drop_index(
        "ix_documents_organizations_gin", table_name="documents", postgresql_using="gin"
    )
    op.drop_index(
        "ix_documents_metadata_gin", table_name="documents", postgresql_using="gin"
    )
    op.drop_index(op.f("ix_documents_current_content_hash"), table_name="documents")
    op.drop_table("documents")
    op.drop_table("workflow_jobs")
    op.drop_table("document_types")
    # ### end Alembic commands ###
